### ISSUE TITLE
Move Tutorials to quarto!

### ISSUE THREAD

**Issue by alaindanet** [BecksLab/JuliaTutorials_BecksLab#4]
The goal is to write the Julia tutorials with [`quarto`](https://quarto.org/docs/computations/julia.html), the new Rmardownish that supports multiple languages!

This change can live in the [quartoBEFWM2 branch](https://github.com/BecksLab/JuliaTutorials_BecksLab/tree/quartoBEFWM2).

- [ ] Doc 1
- [ ] Doc 2
- [ ] Doc 3
- [ ] Doc 4
- [ ] Doc 5
- [ ] Doc 6
- [ ] Doc 7

**Comment by TanyaS08** [comment]
Resolved
